on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip Release
        # You may pin to the exact commit or the version.
        # uses: TheDoctor0/zip-release@a24011d8d445e4da5935a7e73c1f98e22a439464
        uses: TheDoctor0/zip-release@0.7.1
        with:
          # Filename for archive
          filename: resources.zip
          # List of excluded files / directories
